proxy:
  title: imongr
  logo-url: https://raw.githubusercontent.com/mong/imongr/master/pkgdown/favicon/apple-touch-icon-152x152.png
  favicon-path: /opt/shinyproxy/favicon.ico
  hide-navbar: true
  landing-page: /app_direct/imongr
  port: 8080
  container-wait-time: 20000
  authentication: openid
  admin-groups: manager
  openid:
    auth-url: https://dev-4bsfd97d.eu.auth0.com/authorize
    token-url: https://dev-4bsfd97d.eu.auth0.com/oauth/token
    jwks-url: https://dev-4bsfd97d.eu.auth0.com/.well-known/jwks.json
    client-id: ${OPENID_CLIENT_ID}
    client-secret: ${OPENID_CLIENT_SECRET}
    roles-claim: https://imongr.skde.org/shinyproxy_roles
    logout-url: https://dev-4bsfd97d.eu.auth0.com/v2/logout?returnTo=https%3A%2F%2Fimongr.skde.org
  docker:
    internal-networking: true
  container-log-path: s3://shinyproxy-apps-log
  container-log-s3-access-key: ${AWS_S3_ACCESS_KEY}
  container-log-s3-access-secret: ${AWS_S3_ACCESS_SECRET}
  container-log-s3-endpoint: https://s3-eu-west-1.amazonaws.com
  specs:
  - id: imongr
    display-name: imongr
    container-cmd: ["R", "-e", "options(shiny.port=3838,shiny.host='0.0.0.0'); imongr::run_app()"]
    container-image: hnskde/imongr
    container-network: mongr-net
    container-env:
      IMONGR_DB_HOST: ${IMONGR_DB_HOST}
      IMONGR_DB_HOST_VERIFY: ${IMONGR_DB_HOST_VERIFY}
      IMONGR_DB_HOST_QA: ${IMONGR_DB_HOST_QA}
      IMONGR_DB_NAME: ${IMONGR_DB_NAME}
      IMONGR_DB_USER: ${IMONGR_DB_USER}
      IMONGR_DB_PASS: ${IMONGR_DB_PASS}
      IMONGR_ADMINER_URL: ${IMONGR_ADMINER_URL}
server:
  #useForwardHeaders: true
  forward-headers-strategy: native
spring:
  servlet:
    multipart:
      max-file-size: 90MB
      max-request-size: 100MB
logging:
  level:
    root: INFO
